#!/usr/bin/env python3
"""Generate resources/web-shared/dxcc.js from AD1C's cty.dat.

The browser needs a callsign -> DXCC entity lookup (FT8 "new one" stars and the
entity column).  cty.dat (https://www.country-files.com/) is the de-facto
prefix table used by WSJT-X, N1MM and friends; this script folds it into one
small JS file so both builds ship it as a plain asset.

Usage:
    tools/build-dxcc.py                # download the current cty.dat
    tools/build-dxcc.py path/to/cty.dat

Re-run when a new cty.dat is out and commit the regenerated dxcc.js; the
version marker (VERyyyymmdd) is kept in the file header.
"""

import json
import re
import sys
import urllib.request
from pathlib import Path

CTY_URL = "https://www.country-files.com/cty/cty.dat"
OUT = Path(__file__).resolve().parent.parent / "resources" / "web-shared" / "dxcc.js"

# cty.dat prefix override suffixes: (cq)[itu]<lat/lon>{cont}~tz~
OVERRIDES = re.compile(r"\(\d+\)|\[\d+\]|<[^>]*>|\{[^}]*\}|~[^~]*~")


def parse(text):
    entities = []          # [name, primaryPrefix, continent, cq, itu]
    prefixes = {}          # prefix -> entity index
    exact = {}             # full call -> entity index
    version = ""
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        head = lines[i]
        i += 1
        if not head.strip() or head.startswith(" "):
            continue
        f = [x.strip() for x in head.split(":")]
        if len(f) < 8:
            continue
        name, cq, itu, cont, prim = f[0], int(f[1]), int(f[2]), f[3], f[7]
        body = ""
        while i < len(lines):
            body += lines[i].strip()
            i += 1
            if body.endswith(";"):
                break
        body = body.rstrip(";")
        # A leading '*' marks a WAE-only entity (Sicily, European Turkey,
        # Shetland...).  Those are not DXCC entities: skip them so their
        # prefixes fall through to the parent DXCC entity.
        if prim.startswith("*"):
            for tok in body.split(","):
                m = re.search(r"VER(\d{8})", tok)
                if m:
                    version = m.group(1)
            continue
        idx = len(entities)
        entities.append([name, prim, cont, cq, itu])
        for tok in body.split(","):
            tok = tok.strip()
            if not tok:
                continue
            is_exact = tok.startswith("=")
            tok = OVERRIDES.sub("", tok.lstrip("="))
            if not tok:
                continue
            m = re.fullmatch(r"VER(\d{8})", tok)
            if m:
                version = m.group(1)
                continue
            (exact if is_exact else prefixes)[tok.upper()] = idx
    return entities, prefixes, exact, version


TEMPLATE = """// DXCC entity lookup for the browser.  GENERATED by tools/build-dxcc.py from
// AD1C's cty.dat (https://www.country-files.com/), version %(version)s.
// Do not edit by hand: re-run the script to update.
//
//   dxccLookup('IZ1ABC')      -> { name: 'Italy', prefix: 'I', cont: 'EU', cq: 15, itu: 28 }
//   dxccLookup('VP2E/K1ABC')  -> Anguilla; dxccLookup('K1ABC/MM') -> null
(function () {
    'use strict';
    var E = %(entities)s;
    var P = %(prefixes)s;
    var X = %(exact)s;
    var cache = {};
    // Suffixes that never change the entity (and /MM, /AM which have none).
    var NEUTRAL = { P: 1, M: 1, QRP: 1, A: 1, B: 1, R: 1, LH: 1, J: 1, E: 1 };
    function entity(i) {
        var e = E[i];
        return { name: e[0], prefix: e[1], cont: e[2], cq: e[3], itu: e[4] };
    }
    function longest(base) {
        for (var n = base.length; n > 0; n--) {
            var i = P[base.slice(0, n)];
            if (i !== undefined) return i;
        }
        return -1;
    }
    function resolve(call) {
        if (X[call] !== undefined) return X[call];
        var parts = call.split('/');
        if (parts.indexOf('MM') > 0 || parts.indexOf('AM') > 0) return -1;
        var base = parts[0];
        if (parts.length > 1) {
            var cands = [];
            for (var k = 0; k < parts.length; k++) {
                var p = parts[k];
                if (!p || (k > 0 && (NEUTRAL[p] || /^\\d$/.test(p)))) continue;
                cands.push(p);
            }
            if (cands.length) {
                // The shorter part is the prefix designator (VP2E/K1ABC,
                // K1ABC/VE3); equal lengths keep the first.
                base = cands[0];
                for (var c = 1; c < cands.length; c++)
                    if (cands[c].length < base.length) base = cands[c];
            }
            if (X[base] !== undefined) return X[base];
        }
        return longest(base);
    }
    function dxccLookup(call) {
        call = String(call || '').toUpperCase().trim().replace(/^<(.*)>$/, '$1');
        // A callsign has a digit followed (somewhere) by a letter; this
        // rejects grids (FN42), reports (-05, R+03) and RR73/73 tokens.
        if (!call || /[^A-Z0-9\\/]/.test(call) || !/\\d[A-Z0-9\\/]*[A-Z]/.test(call)) return null;
        var i = cache[call];
        if (i === undefined) { i = resolve(call); cache[call] = i; }
        return i < 0 ? null : entity(i);
    }
    dxccLookup.version = '%(version)s';
    dxccLookup.entityCount = E.length;
    window.dxccLookup = dxccLookup;
})();
"""


def main():
    if len(sys.argv) > 1:
        text = Path(sys.argv[1]).read_text(encoding="utf-8", errors="replace")
    else:
        with urllib.request.urlopen(CTY_URL, timeout=30) as r:
            text = r.read().decode("utf-8", errors="replace")
    entities, prefixes, exact, version = parse(text)
    if not entities or not version:
        sys.exit("cty.dat parse failed (no entities or no VER marker)")
    compact = dict(separators=(",", ":"), ensure_ascii=False)
    OUT.write_text(TEMPLATE % {
        "version": version,
        "entities": json.dumps(entities, **compact),
        "prefixes": json.dumps(prefixes, **compact),
        "exact": json.dumps(exact, **compact),
    }, encoding="utf-8")
    print(f"{OUT}: {len(entities)} entities, {len(prefixes)} prefixes, "
          f"{len(exact)} exact calls, cty.dat VER{version}")


if __name__ == "__main__":
    main()
